---
- name: Add APT key for ZFS PPA
  apt_key:
    id: 4AB0F789CBA31744CC7DA76A8CF63AD3F06FC659
    keyserver: keyserver.ubuntu.com
  when: ansible_distribution == "Debian"

- name: Add ZFS PPA for Debian
  apt_repository:
    repo: deb http://ppa.launchpad.net/jonathonf/zfs-debian/ubuntu xenial main
  when: ansible_distribution == "Debian" and ansible_distribution_release == "stretch"

- name: Install ZFS package
  apt:
    name: zfsutils-linux

- name: Add zfs module to /etc/modules
  lineinfile:
    dest: /etc/modules
    line: 'zfs'
    state: present
  register: kernelmodules

- name: Configure ZFS kernel parameters
  template:
    src: zfs.conf.j2
    dest: /etc/modprobe.d/zfs.conf

- name: Reload kernel modules
  service:
    name: systemd-modules-load
    state: restarted
  when: kernelmodules.changed
