---
- name: Update apt repositories cache
  apt:
    update_cache: yes
  changed_when: false
  when: ansible_pkg_mgr == "apt"

- name: Install ZFS apt packages
  apt:
    name: "{{ item }}"
  with_items:
    - zfsutils-linux
    - zfs-initramfs
    - zfs-zed
    - zfs-doc
  when: ansible_pkg_mgr == "apt"

- name: Add zfs module to /etc/modules
  lineinfile:
    dest: /etc/modules
    line: 'zfs'
    state: present
  register: kernelmodules

- name: Reload kernel modules
  service:
    name: systemd-modules-load
    state: restarted
  when: kernelmodules.changed
