---
- import_tasks: install.yml
- include_tasks: configure_filesystems.yml
  with_items: 
    - "{{ zfs_filesystems }}"
  loop_control:
    loop_var: "fs"
  when: zfs_filesystems is defined
  tags:
    - zfs
    - zfs_filesystems

- include_tasks: configure_zvols.yml
  with_items: 
    - "{{ zvols }}"
  loop_control:
    loop_var: "zvol"
  when: zvols is defined
  tags:
    - zfs
    - zfs_zvols

- include_tasks: detect_nfs.yml
  with_items:
    - "{{ zfs_filesystems }}"
  loop_control:
    loop_var: "fs"
  when: zfs_filesystems is defined
  tags:
    - zfs
    - zfs_nfs

- import_tasks: scrub_timer.yml
  tags:
    - zfs
    - zfs_scrub