---
- name: Check if NFS packages are needed
  zfs_facts:
    name: "{{ root_prefix }}/{{ item.name }}"
    properties: "sharenfs"
  ignore_errors: True
  register: no_nfs_datasets
  with_items:
    - "{{ filesystems }}"
  failed_when: ansible_zfs_datasets[0].sharenfs != "off"

- name: Install NFS server package
  apt:
    name: nfs-kernel-server
  when: (ansible_pkg_mgr == "apt") and (no_nfs_datasets |failed)

- name: Enable and (re-)start NFS server
  service:
    name: nfs-kernel-server.service
    state: started
    enabled: true
  when: no_nfs_datasets |failed