---
- name: Check if NFS packages are needed
  zfs_facts:
    name: "{{ parent_fs }}/{{ item.name }}"
    properties: "sharenfs"
  ignore_errors: True
  register: no_nfs_datasets
  with_items:
    - "{{ filesystems }}"
  changed_when: ansible_zfs_datasets[0].sharenfs != "off"

#no need to update cache, it's done in install.yml

- name: Install NFS server package
  apt:
    name: nfs-kernel-server
  when: (ansible_pkg_mgr == "apt") and (no_nfs_datasets.changed)

- name: Enable and (re-)start NFS server
  service:
    name: nfs-kernel-server.service
    state: started
    enabled: true
  when: (ansible_service_mgr == "systemd") and (no_nfs_datasets.changed)