---
- name: Install NFS server package
  apt:
    name: nfs-kernel-server
  when: ansible_pkg_mgr == "apt"

- name: Enable and start NFS server
  service:
    name: nfs-kernel-server.service
    state: started
    enabled: True
  when: ansible_service_mgr == "systemd"

- name: Save NFS exports
  copy:
    src: /var/lib/nfs/etab
    dest: /etc/exports.d/zfs-storage-ansible.exports
    remote_src: True
